name: iOS Build and TestFlight Upload

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build web application
      run: npm run build
      
    - name: Setup iOS dependencies
      run: |
        npm install -g @capacitor/cli
        npx cap sync ios
        
    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Install CocoaPods dependencies
      run: |
        cd ios/App
        pod install
        
    - name: Import Code-Signing Certificates
      uses: Apple-Actions/import-codesign-certs@v2
      with:
        p12-file-base64: ${{ secrets.CERT_P12 }}
        p12-password: ${{ secrets.CERT_P12_PASSWORD }}
        
    - name: Install Provisioning Profile
      uses: Apple-Actions/download-provisioning-profiles@v1
      with:
        bundle-id: com.dimetime.app
        issuer-id: ${{ secrets.ASC_ISSUER_ID }}
        api-key-id: ${{ secrets.ASC_KEY_ID }}
        api-private-key: ${{ secrets.ASC_API_KEY }}
        
    - name: Build iOS App
      run: |
        cd ios/App
        xcodebuild \
          -workspace App.xcworkspace \
          -scheme App \
          -configuration Release \
          -destination generic/platform=iOS \
          -archivePath App.xcarchive \
          archive
          
    - name: Export IPA
      run: |
        cd ios/App
        xcodebuild \
          -exportArchive \
          -archivePath App.xcarchive \
          -exportOptionsPlist ../../build-config/ExportOptions.plist \
          -exportPath ./build \
          -allowProvisioningUpdates
          
    - name: Upload to TestFlight
      uses: Apple-Actions/upload-testflight-build@v1
      with:
        app-path: ios/App/build/App.ipa
        issuer-id: ${{ secrets.ASC_ISSUER_ID }}
        api-key-id: ${{ secrets.ASC_KEY_ID }}
        api-private-key: ${{ secrets.ASC_API_KEY }}
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ios-build-artifacts
        path: |
          ios/App/build/
          ios/App/App.xcarchive/
